language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.4
  - nightly

codecov: true
coveralls: true

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - export GKSwstype=100
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait 30 julia --project=docs/ docs/make.jl
      after_success: skip
